// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/youxihu/casey/internal/data/ent/caseytrigger"
	"github.com/youxihu/casey/internal/data/ent/predicate"
)

// CaseyTriggerQuery is the builder for querying CaseyTrigger entities.
type CaseyTriggerQuery struct {
	config
	ctx        *QueryContext
	order      []caseytrigger.OrderOption
	inters     []Interceptor
	predicates []predicate.CaseyTrigger
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CaseyTriggerQuery builder.
func (ctq *CaseyTriggerQuery) Where(ps ...predicate.CaseyTrigger) *CaseyTriggerQuery {
	ctq.predicates = append(ctq.predicates, ps...)
	return ctq
}

// Limit the number of records to be returned by this query.
func (ctq *CaseyTriggerQuery) Limit(limit int) *CaseyTriggerQuery {
	ctq.ctx.Limit = &limit
	return ctq
}

// Offset to start from.
func (ctq *CaseyTriggerQuery) Offset(offset int) *CaseyTriggerQuery {
	ctq.ctx.Offset = &offset
	return ctq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ctq *CaseyTriggerQuery) Unique(unique bool) *CaseyTriggerQuery {
	ctq.ctx.Unique = &unique
	return ctq
}

// Order specifies how the records should be ordered.
func (ctq *CaseyTriggerQuery) Order(o ...caseytrigger.OrderOption) *CaseyTriggerQuery {
	ctq.order = append(ctq.order, o...)
	return ctq
}

// First returns the first CaseyTrigger entity from the query.
// Returns a *NotFoundError when no CaseyTrigger was found.
func (ctq *CaseyTriggerQuery) First(ctx context.Context) (*CaseyTrigger, error) {
	nodes, err := ctq.Limit(1).All(setContextOp(ctx, ctq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{caseytrigger.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ctq *CaseyTriggerQuery) FirstX(ctx context.Context) *CaseyTrigger {
	node, err := ctq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CaseyTrigger ID from the query.
// Returns a *NotFoundError when no CaseyTrigger ID was found.
func (ctq *CaseyTriggerQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = ctq.Limit(1).IDs(setContextOp(ctx, ctq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{caseytrigger.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ctq *CaseyTriggerQuery) FirstIDX(ctx context.Context) int64 {
	id, err := ctq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CaseyTrigger entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CaseyTrigger entity is found.
// Returns a *NotFoundError when no CaseyTrigger entities are found.
func (ctq *CaseyTriggerQuery) Only(ctx context.Context) (*CaseyTrigger, error) {
	nodes, err := ctq.Limit(2).All(setContextOp(ctx, ctq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{caseytrigger.Label}
	default:
		return nil, &NotSingularError{caseytrigger.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ctq *CaseyTriggerQuery) OnlyX(ctx context.Context) *CaseyTrigger {
	node, err := ctq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CaseyTrigger ID in the query.
// Returns a *NotSingularError when more than one CaseyTrigger ID is found.
// Returns a *NotFoundError when no entities are found.
func (ctq *CaseyTriggerQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = ctq.Limit(2).IDs(setContextOp(ctx, ctq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{caseytrigger.Label}
	default:
		err = &NotSingularError{caseytrigger.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ctq *CaseyTriggerQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := ctq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CaseyTriggers.
func (ctq *CaseyTriggerQuery) All(ctx context.Context) ([]*CaseyTrigger, error) {
	ctx = setContextOp(ctx, ctq.ctx, ent.OpQueryAll)
	if err := ctq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CaseyTrigger, *CaseyTriggerQuery]()
	return withInterceptors[[]*CaseyTrigger](ctx, ctq, qr, ctq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ctq *CaseyTriggerQuery) AllX(ctx context.Context) []*CaseyTrigger {
	nodes, err := ctq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CaseyTrigger IDs.
func (ctq *CaseyTriggerQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if ctq.ctx.Unique == nil && ctq.path != nil {
		ctq.Unique(true)
	}
	ctx = setContextOp(ctx, ctq.ctx, ent.OpQueryIDs)
	if err = ctq.Select(caseytrigger.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ctq *CaseyTriggerQuery) IDsX(ctx context.Context) []int64 {
	ids, err := ctq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ctq *CaseyTriggerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ctq.ctx, ent.OpQueryCount)
	if err := ctq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ctq, querierCount[*CaseyTriggerQuery](), ctq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ctq *CaseyTriggerQuery) CountX(ctx context.Context) int {
	count, err := ctq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ctq *CaseyTriggerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ctq.ctx, ent.OpQueryExist)
	switch _, err := ctq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ctq *CaseyTriggerQuery) ExistX(ctx context.Context) bool {
	exist, err := ctq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CaseyTriggerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ctq *CaseyTriggerQuery) Clone() *CaseyTriggerQuery {
	if ctq == nil {
		return nil
	}
	return &CaseyTriggerQuery{
		config:     ctq.config,
		ctx:        ctq.ctx.Clone(),
		order:      append([]caseytrigger.OrderOption{}, ctq.order...),
		inters:     append([]Interceptor{}, ctq.inters...),
		predicates: append([]predicate.CaseyTrigger{}, ctq.predicates...),
		// clone intermediate query.
		sql:       ctq.sql.Clone(),
		path:      ctq.path,
		modifiers: append([]func(*sql.Selector){}, ctq.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Executor string `json:"executor,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CaseyTrigger.Query().
//		GroupBy(caseytrigger.FieldExecutor).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ctq *CaseyTriggerQuery) GroupBy(field string, fields ...string) *CaseyTriggerGroupBy {
	ctq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CaseyTriggerGroupBy{build: ctq}
	grbuild.flds = &ctq.ctx.Fields
	grbuild.label = caseytrigger.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Executor string `json:"executor,omitempty"`
//	}
//
//	client.CaseyTrigger.Query().
//		Select(caseytrigger.FieldExecutor).
//		Scan(ctx, &v)
func (ctq *CaseyTriggerQuery) Select(fields ...string) *CaseyTriggerSelect {
	ctq.ctx.Fields = append(ctq.ctx.Fields, fields...)
	sbuild := &CaseyTriggerSelect{CaseyTriggerQuery: ctq}
	sbuild.label = caseytrigger.Label
	sbuild.flds, sbuild.scan = &ctq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CaseyTriggerSelect configured with the given aggregations.
func (ctq *CaseyTriggerQuery) Aggregate(fns ...AggregateFunc) *CaseyTriggerSelect {
	return ctq.Select().Aggregate(fns...)
}

func (ctq *CaseyTriggerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ctq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ctq); err != nil {
				return err
			}
		}
	}
	for _, f := range ctq.ctx.Fields {
		if !caseytrigger.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ctq.path != nil {
		prev, err := ctq.path(ctx)
		if err != nil {
			return err
		}
		ctq.sql = prev
	}
	return nil
}

func (ctq *CaseyTriggerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CaseyTrigger, error) {
	var (
		nodes = []*CaseyTrigger{}
		_spec = ctq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CaseyTrigger).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CaseyTrigger{config: ctq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(ctq.modifiers) > 0 {
		_spec.Modifiers = ctq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ctq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ctq *CaseyTriggerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ctq.querySpec()
	if len(ctq.modifiers) > 0 {
		_spec.Modifiers = ctq.modifiers
	}
	_spec.Node.Columns = ctq.ctx.Fields
	if len(ctq.ctx.Fields) > 0 {
		_spec.Unique = ctq.ctx.Unique != nil && *ctq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ctq.driver, _spec)
}

func (ctq *CaseyTriggerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(caseytrigger.Table, caseytrigger.Columns, sqlgraph.NewFieldSpec(caseytrigger.FieldID, field.TypeInt64))
	_spec.From = ctq.sql
	if unique := ctq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ctq.path != nil {
		_spec.Unique = true
	}
	if fields := ctq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, caseytrigger.FieldID)
		for i := range fields {
			if fields[i] != caseytrigger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ctq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ctq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ctq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ctq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ctq *CaseyTriggerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ctq.driver.Dialect())
	t1 := builder.Table(caseytrigger.Table)
	columns := ctq.ctx.Fields
	if len(columns) == 0 {
		columns = caseytrigger.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ctq.sql != nil {
		selector = ctq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ctq.ctx.Unique != nil && *ctq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range ctq.modifiers {
		m(selector)
	}
	for _, p := range ctq.predicates {
		p(selector)
	}
	for _, p := range ctq.order {
		p(selector)
	}
	if offset := ctq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ctq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ctq *CaseyTriggerQuery) Modify(modifiers ...func(s *sql.Selector)) *CaseyTriggerSelect {
	ctq.modifiers = append(ctq.modifiers, modifiers...)
	return ctq.Select()
}

// CaseyTriggerGroupBy is the group-by builder for CaseyTrigger entities.
type CaseyTriggerGroupBy struct {
	selector
	build *CaseyTriggerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ctgb *CaseyTriggerGroupBy) Aggregate(fns ...AggregateFunc) *CaseyTriggerGroupBy {
	ctgb.fns = append(ctgb.fns, fns...)
	return ctgb
}

// Scan applies the selector query and scans the result into the given value.
func (ctgb *CaseyTriggerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ctgb.build.ctx, ent.OpQueryGroupBy)
	if err := ctgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CaseyTriggerQuery, *CaseyTriggerGroupBy](ctx, ctgb.build, ctgb, ctgb.build.inters, v)
}

func (ctgb *CaseyTriggerGroupBy) sqlScan(ctx context.Context, root *CaseyTriggerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ctgb.fns))
	for _, fn := range ctgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ctgb.flds)+len(ctgb.fns))
		for _, f := range *ctgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ctgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ctgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CaseyTriggerSelect is the builder for selecting fields of CaseyTrigger entities.
type CaseyTriggerSelect struct {
	*CaseyTriggerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cts *CaseyTriggerSelect) Aggregate(fns ...AggregateFunc) *CaseyTriggerSelect {
	cts.fns = append(cts.fns, fns...)
	return cts
}

// Scan applies the selector query and scans the result into the given value.
func (cts *CaseyTriggerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cts.ctx, ent.OpQuerySelect)
	if err := cts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CaseyTriggerQuery, *CaseyTriggerSelect](ctx, cts.CaseyTriggerQuery, cts, cts.inters, v)
}

func (cts *CaseyTriggerSelect) sqlScan(ctx context.Context, root *CaseyTriggerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cts.fns))
	for _, fn := range cts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (cts *CaseyTriggerSelect) Modify(modifiers ...func(s *sql.Selector)) *CaseyTriggerSelect {
	cts.modifiers = append(cts.modifiers, modifiers...)
	return cts
}
