// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/youxihu/casey/internal/data/ent/caseytrigger"
	"github.com/youxihu/casey/internal/data/ent/predicate"
)

// CaseyTriggerDelete is the builder for deleting a CaseyTrigger entity.
type CaseyTriggerDelete struct {
	config
	hooks    []Hook
	mutation *CaseyTriggerMutation
}

// Where appends a list predicates to the CaseyTriggerDelete builder.
func (ctd *CaseyTriggerDelete) Where(ps ...predicate.CaseyTrigger) *CaseyTriggerDelete {
	ctd.mutation.Where(ps...)
	return ctd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ctd *CaseyTriggerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ctd.sqlExec, ctd.mutation, ctd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ctd *CaseyTriggerDelete) ExecX(ctx context.Context) int {
	n, err := ctd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ctd *CaseyTriggerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(caseytrigger.Table, sqlgraph.NewFieldSpec(caseytrigger.FieldID, field.TypeInt64))
	if ps := ctd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ctd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ctd.mutation.done = true
	return affected, err
}

// CaseyTriggerDeleteOne is the builder for deleting a single CaseyTrigger entity.
type CaseyTriggerDeleteOne struct {
	ctd *CaseyTriggerDelete
}

// Where appends a list predicates to the CaseyTriggerDelete builder.
func (ctdo *CaseyTriggerDeleteOne) Where(ps ...predicate.CaseyTrigger) *CaseyTriggerDeleteOne {
	ctdo.ctd.mutation.Where(ps...)
	return ctdo
}

// Exec executes the deletion query.
func (ctdo *CaseyTriggerDeleteOne) Exec(ctx context.Context) error {
	n, err := ctdo.ctd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{caseytrigger.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ctdo *CaseyTriggerDeleteOne) ExecX(ctx context.Context) {
	if err := ctdo.Exec(ctx); err != nil {
		panic(err)
	}
}
