// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/youxihu/casey/internal/data/ent/caseyinspections"
	"github.com/youxihu/casey/internal/data/ent/predicate"
)

// CaseyInspectionsQuery is the builder for querying CaseyInspections entities.
type CaseyInspectionsQuery struct {
	config
	ctx        *QueryContext
	order      []caseyinspections.OrderOption
	inters     []Interceptor
	predicates []predicate.CaseyInspections
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CaseyInspectionsQuery builder.
func (ciq *CaseyInspectionsQuery) Where(ps ...predicate.CaseyInspections) *CaseyInspectionsQuery {
	ciq.predicates = append(ciq.predicates, ps...)
	return ciq
}

// Limit the number of records to be returned by this query.
func (ciq *CaseyInspectionsQuery) Limit(limit int) *CaseyInspectionsQuery {
	ciq.ctx.Limit = &limit
	return ciq
}

// Offset to start from.
func (ciq *CaseyInspectionsQuery) Offset(offset int) *CaseyInspectionsQuery {
	ciq.ctx.Offset = &offset
	return ciq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ciq *CaseyInspectionsQuery) Unique(unique bool) *CaseyInspectionsQuery {
	ciq.ctx.Unique = &unique
	return ciq
}

// Order specifies how the records should be ordered.
func (ciq *CaseyInspectionsQuery) Order(o ...caseyinspections.OrderOption) *CaseyInspectionsQuery {
	ciq.order = append(ciq.order, o...)
	return ciq
}

// First returns the first CaseyInspections entity from the query.
// Returns a *NotFoundError when no CaseyInspections was found.
func (ciq *CaseyInspectionsQuery) First(ctx context.Context) (*CaseyInspections, error) {
	nodes, err := ciq.Limit(1).All(setContextOp(ctx, ciq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{caseyinspections.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ciq *CaseyInspectionsQuery) FirstX(ctx context.Context) *CaseyInspections {
	node, err := ciq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CaseyInspections ID from the query.
// Returns a *NotFoundError when no CaseyInspections ID was found.
func (ciq *CaseyInspectionsQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = ciq.Limit(1).IDs(setContextOp(ctx, ciq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{caseyinspections.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ciq *CaseyInspectionsQuery) FirstIDX(ctx context.Context) int64 {
	id, err := ciq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CaseyInspections entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CaseyInspections entity is found.
// Returns a *NotFoundError when no CaseyInspections entities are found.
func (ciq *CaseyInspectionsQuery) Only(ctx context.Context) (*CaseyInspections, error) {
	nodes, err := ciq.Limit(2).All(setContextOp(ctx, ciq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{caseyinspections.Label}
	default:
		return nil, &NotSingularError{caseyinspections.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ciq *CaseyInspectionsQuery) OnlyX(ctx context.Context) *CaseyInspections {
	node, err := ciq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CaseyInspections ID in the query.
// Returns a *NotSingularError when more than one CaseyInspections ID is found.
// Returns a *NotFoundError when no entities are found.
func (ciq *CaseyInspectionsQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = ciq.Limit(2).IDs(setContextOp(ctx, ciq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{caseyinspections.Label}
	default:
		err = &NotSingularError{caseyinspections.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ciq *CaseyInspectionsQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := ciq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CaseyInspectionsSlice.
func (ciq *CaseyInspectionsQuery) All(ctx context.Context) ([]*CaseyInspections, error) {
	ctx = setContextOp(ctx, ciq.ctx, ent.OpQueryAll)
	if err := ciq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CaseyInspections, *CaseyInspectionsQuery]()
	return withInterceptors[[]*CaseyInspections](ctx, ciq, qr, ciq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ciq *CaseyInspectionsQuery) AllX(ctx context.Context) []*CaseyInspections {
	nodes, err := ciq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CaseyInspections IDs.
func (ciq *CaseyInspectionsQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if ciq.ctx.Unique == nil && ciq.path != nil {
		ciq.Unique(true)
	}
	ctx = setContextOp(ctx, ciq.ctx, ent.OpQueryIDs)
	if err = ciq.Select(caseyinspections.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ciq *CaseyInspectionsQuery) IDsX(ctx context.Context) []int64 {
	ids, err := ciq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ciq *CaseyInspectionsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ciq.ctx, ent.OpQueryCount)
	if err := ciq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ciq, querierCount[*CaseyInspectionsQuery](), ciq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ciq *CaseyInspectionsQuery) CountX(ctx context.Context) int {
	count, err := ciq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ciq *CaseyInspectionsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ciq.ctx, ent.OpQueryExist)
	switch _, err := ciq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ciq *CaseyInspectionsQuery) ExistX(ctx context.Context) bool {
	exist, err := ciq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CaseyInspectionsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ciq *CaseyInspectionsQuery) Clone() *CaseyInspectionsQuery {
	if ciq == nil {
		return nil
	}
	return &CaseyInspectionsQuery{
		config:     ciq.config,
		ctx:        ciq.ctx.Clone(),
		order:      append([]caseyinspections.OrderOption{}, ciq.order...),
		inters:     append([]Interceptor{}, ciq.inters...),
		predicates: append([]predicate.CaseyInspections{}, ciq.predicates...),
		// clone intermediate query.
		sql:       ciq.sql.Clone(),
		path:      ciq.path,
		modifiers: append([]func(*sql.Selector){}, ciq.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Timestamp string `json:"timestamp,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CaseyInspections.Query().
//		GroupBy(caseyinspections.FieldTimestamp).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ciq *CaseyInspectionsQuery) GroupBy(field string, fields ...string) *CaseyInspectionsGroupBy {
	ciq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CaseyInspectionsGroupBy{build: ciq}
	grbuild.flds = &ciq.ctx.Fields
	grbuild.label = caseyinspections.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Timestamp string `json:"timestamp,omitempty"`
//	}
//
//	client.CaseyInspections.Query().
//		Select(caseyinspections.FieldTimestamp).
//		Scan(ctx, &v)
func (ciq *CaseyInspectionsQuery) Select(fields ...string) *CaseyInspectionsSelect {
	ciq.ctx.Fields = append(ciq.ctx.Fields, fields...)
	sbuild := &CaseyInspectionsSelect{CaseyInspectionsQuery: ciq}
	sbuild.label = caseyinspections.Label
	sbuild.flds, sbuild.scan = &ciq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CaseyInspectionsSelect configured with the given aggregations.
func (ciq *CaseyInspectionsQuery) Aggregate(fns ...AggregateFunc) *CaseyInspectionsSelect {
	return ciq.Select().Aggregate(fns...)
}

func (ciq *CaseyInspectionsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ciq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ciq); err != nil {
				return err
			}
		}
	}
	for _, f := range ciq.ctx.Fields {
		if !caseyinspections.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ciq.path != nil {
		prev, err := ciq.path(ctx)
		if err != nil {
			return err
		}
		ciq.sql = prev
	}
	return nil
}

func (ciq *CaseyInspectionsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CaseyInspections, error) {
	var (
		nodes = []*CaseyInspections{}
		_spec = ciq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CaseyInspections).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CaseyInspections{config: ciq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(ciq.modifiers) > 0 {
		_spec.Modifiers = ciq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ciq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ciq *CaseyInspectionsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ciq.querySpec()
	if len(ciq.modifiers) > 0 {
		_spec.Modifiers = ciq.modifiers
	}
	_spec.Node.Columns = ciq.ctx.Fields
	if len(ciq.ctx.Fields) > 0 {
		_spec.Unique = ciq.ctx.Unique != nil && *ciq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ciq.driver, _spec)
}

func (ciq *CaseyInspectionsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(caseyinspections.Table, caseyinspections.Columns, sqlgraph.NewFieldSpec(caseyinspections.FieldID, field.TypeInt64))
	_spec.From = ciq.sql
	if unique := ciq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ciq.path != nil {
		_spec.Unique = true
	}
	if fields := ciq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, caseyinspections.FieldID)
		for i := range fields {
			if fields[i] != caseyinspections.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ciq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ciq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ciq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ciq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ciq *CaseyInspectionsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ciq.driver.Dialect())
	t1 := builder.Table(caseyinspections.Table)
	columns := ciq.ctx.Fields
	if len(columns) == 0 {
		columns = caseyinspections.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ciq.sql != nil {
		selector = ciq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ciq.ctx.Unique != nil && *ciq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range ciq.modifiers {
		m(selector)
	}
	for _, p := range ciq.predicates {
		p(selector)
	}
	for _, p := range ciq.order {
		p(selector)
	}
	if offset := ciq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ciq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ciq *CaseyInspectionsQuery) Modify(modifiers ...func(s *sql.Selector)) *CaseyInspectionsSelect {
	ciq.modifiers = append(ciq.modifiers, modifiers...)
	return ciq.Select()
}

// CaseyInspectionsGroupBy is the group-by builder for CaseyInspections entities.
type CaseyInspectionsGroupBy struct {
	selector
	build *CaseyInspectionsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cigb *CaseyInspectionsGroupBy) Aggregate(fns ...AggregateFunc) *CaseyInspectionsGroupBy {
	cigb.fns = append(cigb.fns, fns...)
	return cigb
}

// Scan applies the selector query and scans the result into the given value.
func (cigb *CaseyInspectionsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cigb.build.ctx, ent.OpQueryGroupBy)
	if err := cigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CaseyInspectionsQuery, *CaseyInspectionsGroupBy](ctx, cigb.build, cigb, cigb.build.inters, v)
}

func (cigb *CaseyInspectionsGroupBy) sqlScan(ctx context.Context, root *CaseyInspectionsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cigb.fns))
	for _, fn := range cigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cigb.flds)+len(cigb.fns))
		for _, f := range *cigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CaseyInspectionsSelect is the builder for selecting fields of CaseyInspections entities.
type CaseyInspectionsSelect struct {
	*CaseyInspectionsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cis *CaseyInspectionsSelect) Aggregate(fns ...AggregateFunc) *CaseyInspectionsSelect {
	cis.fns = append(cis.fns, fns...)
	return cis
}

// Scan applies the selector query and scans the result into the given value.
func (cis *CaseyInspectionsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cis.ctx, ent.OpQuerySelect)
	if err := cis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CaseyInspectionsQuery, *CaseyInspectionsSelect](ctx, cis.CaseyInspectionsQuery, cis, cis.inters, v)
}

func (cis *CaseyInspectionsSelect) sqlScan(ctx context.Context, root *CaseyInspectionsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cis.fns))
	for _, fn := range cis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (cis *CaseyInspectionsSelect) Modify(modifiers ...func(s *sql.Selector)) *CaseyInspectionsSelect {
	cis.modifiers = append(cis.modifiers, modifiers...)
	return cis
}
