// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/youxihu/casey/internal/data/ent/caseyinspections"
	"github.com/youxihu/casey/internal/data/ent/predicate"
)

// CaseyInspectionsDelete is the builder for deleting a CaseyInspections entity.
type CaseyInspectionsDelete struct {
	config
	hooks    []Hook
	mutation *CaseyInspectionsMutation
}

// Where appends a list predicates to the CaseyInspectionsDelete builder.
func (cid *CaseyInspectionsDelete) Where(ps ...predicate.CaseyInspections) *CaseyInspectionsDelete {
	cid.mutation.Where(ps...)
	return cid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cid *CaseyInspectionsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cid.sqlExec, cid.mutation, cid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cid *CaseyInspectionsDelete) ExecX(ctx context.Context) int {
	n, err := cid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cid *CaseyInspectionsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(caseyinspections.Table, sqlgraph.NewFieldSpec(caseyinspections.FieldID, field.TypeInt64))
	if ps := cid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cid.mutation.done = true
	return affected, err
}

// CaseyInspectionsDeleteOne is the builder for deleting a single CaseyInspections entity.
type CaseyInspectionsDeleteOne struct {
	cid *CaseyInspectionsDelete
}

// Where appends a list predicates to the CaseyInspectionsDelete builder.
func (cido *CaseyInspectionsDeleteOne) Where(ps ...predicate.CaseyInspections) *CaseyInspectionsDeleteOne {
	cido.cid.mutation.Where(ps...)
	return cido
}

// Exec executes the deletion query.
func (cido *CaseyInspectionsDeleteOne) Exec(ctx context.Context) error {
	n, err := cido.cid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{caseyinspections.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cido *CaseyInspectionsDeleteOne) ExecX(ctx context.Context) {
	if err := cido.Exec(ctx); err != nil {
		panic(err)
	}
}
