// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/youxihu/casey/internal/data/ent/caseyinspections"
	"github.com/youxihu/casey/internal/data/ent/caseytrigger"
	"github.com/youxihu/casey/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	caseyinspectionsFields := schema.CaseyInspections{}.Fields()
	_ = caseyinspectionsFields
	// caseyinspectionsDescCreatedAt is the schema descriptor for created_at field.
	caseyinspectionsDescCreatedAt := caseyinspectionsFields[17].Descriptor()
	// caseyinspections.DefaultCreatedAt holds the default value on creation for the created_at field.
	caseyinspections.DefaultCreatedAt = caseyinspectionsDescCreatedAt.Default.(func() time.Time)
	caseytriggerFields := schema.CaseyTrigger{}.Fields()
	_ = caseytriggerFields
	// caseytriggerDescExecutedAt is the schema descriptor for executed_at field.
	caseytriggerDescExecutedAt := caseytriggerFields[5].Descriptor()
	// caseytrigger.DefaultExecutedAt holds the default value on creation for the executed_at field.
	caseytrigger.DefaultExecutedAt = caseytriggerDescExecutedAt.Default.(func() time.Time)
}
