// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CaseyInspections is the predicate function for caseyinspections builders.
type CaseyInspections func(*sql.Selector)

// CaseyTrigger is the predicate function for caseytrigger builders.
type CaseyTrigger func(*sql.Selector)
