// Code generated by ent, DO NOT EDIT.

package caseyinspections

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/youxihu/casey/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLTE(FieldID, id))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldTimestamp, v))
}

// Hostname applies equality check predicate on the "hostname" field. It's identical to HostnameEQ.
func Hostname(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldHostname, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldIP, v))
}

// Os applies equality check predicate on the "os" field. It's identical to OsEQ.
func Os(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldOs, v))
}

// Uptime applies equality check predicate on the "uptime" field. It's identical to UptimeEQ.
func Uptime(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldUptime, v))
}

// CPU applies equality check predicate on the "cpu" field. It's identical to CPUEQ.
func CPU(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldCPU, v))
}

// CPULoad applies equality check predicate on the "cpu_load" field. It's identical to CPULoadEQ.
func CPULoad(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldCPULoad, v))
}

// Memory applies equality check predicate on the "memory" field. It's identical to MemoryEQ.
func Memory(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldMemory, v))
}

// Disk applies equality check predicate on the "disk" field. It's identical to DiskEQ.
func Disk(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldDisk, v))
}

// DiskIo applies equality check predicate on the "disk_io" field. It's identical to DiskIoEQ.
func DiskIo(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldDiskIo, v))
}

// Router applies equality check predicate on the "router" field. It's identical to RouterEQ.
func Router(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldRouter, v))
}

// NetStats applies equality check predicate on the "net_stats" field. It's identical to NetStatsEQ.
func NetStats(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldNetStats, v))
}

// Processes applies equality check predicate on the "processes" field. It's identical to ProcessesEQ.
func Processes(v int32) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldProcesses, v))
}

// ZombieProcs applies equality check predicate on the "zombie_procs" field. It's identical to ZombieProcsEQ.
func ZombieProcs(v int32) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldZombieProcs, v))
}

// TopProcesses applies equality check predicate on the "top_processes" field. It's identical to TopProcessesEQ.
func TopProcesses(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldTopProcesses, v))
}

// Env applies equality check predicate on the "env" field. It's identical to EnvEQ.
func Env(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldEnv, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldCreatedAt, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLTE(FieldTimestamp, v))
}

// TimestampContains applies the Contains predicate on the "timestamp" field.
func TimestampContains(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContains(FieldTimestamp, v))
}

// TimestampHasPrefix applies the HasPrefix predicate on the "timestamp" field.
func TimestampHasPrefix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasPrefix(FieldTimestamp, v))
}

// TimestampHasSuffix applies the HasSuffix predicate on the "timestamp" field.
func TimestampHasSuffix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasSuffix(FieldTimestamp, v))
}

// TimestampEqualFold applies the EqualFold predicate on the "timestamp" field.
func TimestampEqualFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEqualFold(FieldTimestamp, v))
}

// TimestampContainsFold applies the ContainsFold predicate on the "timestamp" field.
func TimestampContainsFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContainsFold(FieldTimestamp, v))
}

// HostnameEQ applies the EQ predicate on the "hostname" field.
func HostnameEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldHostname, v))
}

// HostnameNEQ applies the NEQ predicate on the "hostname" field.
func HostnameNEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNEQ(FieldHostname, v))
}

// HostnameIn applies the In predicate on the "hostname" field.
func HostnameIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIn(FieldHostname, vs...))
}

// HostnameNotIn applies the NotIn predicate on the "hostname" field.
func HostnameNotIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotIn(FieldHostname, vs...))
}

// HostnameGT applies the GT predicate on the "hostname" field.
func HostnameGT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGT(FieldHostname, v))
}

// HostnameGTE applies the GTE predicate on the "hostname" field.
func HostnameGTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGTE(FieldHostname, v))
}

// HostnameLT applies the LT predicate on the "hostname" field.
func HostnameLT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLT(FieldHostname, v))
}

// HostnameLTE applies the LTE predicate on the "hostname" field.
func HostnameLTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLTE(FieldHostname, v))
}

// HostnameContains applies the Contains predicate on the "hostname" field.
func HostnameContains(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContains(FieldHostname, v))
}

// HostnameHasPrefix applies the HasPrefix predicate on the "hostname" field.
func HostnameHasPrefix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasPrefix(FieldHostname, v))
}

// HostnameHasSuffix applies the HasSuffix predicate on the "hostname" field.
func HostnameHasSuffix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasSuffix(FieldHostname, v))
}

// HostnameEqualFold applies the EqualFold predicate on the "hostname" field.
func HostnameEqualFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEqualFold(FieldHostname, v))
}

// HostnameContainsFold applies the ContainsFold predicate on the "hostname" field.
func HostnameContainsFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContainsFold(FieldHostname, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContainsFold(FieldIP, v))
}

// OsEQ applies the EQ predicate on the "os" field.
func OsEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldOs, v))
}

// OsNEQ applies the NEQ predicate on the "os" field.
func OsNEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNEQ(FieldOs, v))
}

// OsIn applies the In predicate on the "os" field.
func OsIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIn(FieldOs, vs...))
}

// OsNotIn applies the NotIn predicate on the "os" field.
func OsNotIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotIn(FieldOs, vs...))
}

// OsGT applies the GT predicate on the "os" field.
func OsGT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGT(FieldOs, v))
}

// OsGTE applies the GTE predicate on the "os" field.
func OsGTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGTE(FieldOs, v))
}

// OsLT applies the LT predicate on the "os" field.
func OsLT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLT(FieldOs, v))
}

// OsLTE applies the LTE predicate on the "os" field.
func OsLTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLTE(FieldOs, v))
}

// OsContains applies the Contains predicate on the "os" field.
func OsContains(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContains(FieldOs, v))
}

// OsHasPrefix applies the HasPrefix predicate on the "os" field.
func OsHasPrefix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasPrefix(FieldOs, v))
}

// OsHasSuffix applies the HasSuffix predicate on the "os" field.
func OsHasSuffix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasSuffix(FieldOs, v))
}

// OsEqualFold applies the EqualFold predicate on the "os" field.
func OsEqualFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEqualFold(FieldOs, v))
}

// OsContainsFold applies the ContainsFold predicate on the "os" field.
func OsContainsFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContainsFold(FieldOs, v))
}

// UptimeEQ applies the EQ predicate on the "uptime" field.
func UptimeEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldUptime, v))
}

// UptimeNEQ applies the NEQ predicate on the "uptime" field.
func UptimeNEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNEQ(FieldUptime, v))
}

// UptimeIn applies the In predicate on the "uptime" field.
func UptimeIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIn(FieldUptime, vs...))
}

// UptimeNotIn applies the NotIn predicate on the "uptime" field.
func UptimeNotIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotIn(FieldUptime, vs...))
}

// UptimeGT applies the GT predicate on the "uptime" field.
func UptimeGT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGT(FieldUptime, v))
}

// UptimeGTE applies the GTE predicate on the "uptime" field.
func UptimeGTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGTE(FieldUptime, v))
}

// UptimeLT applies the LT predicate on the "uptime" field.
func UptimeLT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLT(FieldUptime, v))
}

// UptimeLTE applies the LTE predicate on the "uptime" field.
func UptimeLTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLTE(FieldUptime, v))
}

// UptimeContains applies the Contains predicate on the "uptime" field.
func UptimeContains(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContains(FieldUptime, v))
}

// UptimeHasPrefix applies the HasPrefix predicate on the "uptime" field.
func UptimeHasPrefix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasPrefix(FieldUptime, v))
}

// UptimeHasSuffix applies the HasSuffix predicate on the "uptime" field.
func UptimeHasSuffix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasSuffix(FieldUptime, v))
}

// UptimeEqualFold applies the EqualFold predicate on the "uptime" field.
func UptimeEqualFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEqualFold(FieldUptime, v))
}

// UptimeContainsFold applies the ContainsFold predicate on the "uptime" field.
func UptimeContainsFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContainsFold(FieldUptime, v))
}

// CPUEQ applies the EQ predicate on the "cpu" field.
func CPUEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldCPU, v))
}

// CPUNEQ applies the NEQ predicate on the "cpu" field.
func CPUNEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNEQ(FieldCPU, v))
}

// CPUIn applies the In predicate on the "cpu" field.
func CPUIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIn(FieldCPU, vs...))
}

// CPUNotIn applies the NotIn predicate on the "cpu" field.
func CPUNotIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotIn(FieldCPU, vs...))
}

// CPUGT applies the GT predicate on the "cpu" field.
func CPUGT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGT(FieldCPU, v))
}

// CPUGTE applies the GTE predicate on the "cpu" field.
func CPUGTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGTE(FieldCPU, v))
}

// CPULT applies the LT predicate on the "cpu" field.
func CPULT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLT(FieldCPU, v))
}

// CPULTE applies the LTE predicate on the "cpu" field.
func CPULTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLTE(FieldCPU, v))
}

// CPUContains applies the Contains predicate on the "cpu" field.
func CPUContains(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContains(FieldCPU, v))
}

// CPUHasPrefix applies the HasPrefix predicate on the "cpu" field.
func CPUHasPrefix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasPrefix(FieldCPU, v))
}

// CPUHasSuffix applies the HasSuffix predicate on the "cpu" field.
func CPUHasSuffix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasSuffix(FieldCPU, v))
}

// CPUEqualFold applies the EqualFold predicate on the "cpu" field.
func CPUEqualFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEqualFold(FieldCPU, v))
}

// CPUContainsFold applies the ContainsFold predicate on the "cpu" field.
func CPUContainsFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContainsFold(FieldCPU, v))
}

// CPULoadEQ applies the EQ predicate on the "cpu_load" field.
func CPULoadEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldCPULoad, v))
}

// CPULoadNEQ applies the NEQ predicate on the "cpu_load" field.
func CPULoadNEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNEQ(FieldCPULoad, v))
}

// CPULoadIn applies the In predicate on the "cpu_load" field.
func CPULoadIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIn(FieldCPULoad, vs...))
}

// CPULoadNotIn applies the NotIn predicate on the "cpu_load" field.
func CPULoadNotIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotIn(FieldCPULoad, vs...))
}

// CPULoadGT applies the GT predicate on the "cpu_load" field.
func CPULoadGT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGT(FieldCPULoad, v))
}

// CPULoadGTE applies the GTE predicate on the "cpu_load" field.
func CPULoadGTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGTE(FieldCPULoad, v))
}

// CPULoadLT applies the LT predicate on the "cpu_load" field.
func CPULoadLT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLT(FieldCPULoad, v))
}

// CPULoadLTE applies the LTE predicate on the "cpu_load" field.
func CPULoadLTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLTE(FieldCPULoad, v))
}

// CPULoadContains applies the Contains predicate on the "cpu_load" field.
func CPULoadContains(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContains(FieldCPULoad, v))
}

// CPULoadHasPrefix applies the HasPrefix predicate on the "cpu_load" field.
func CPULoadHasPrefix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasPrefix(FieldCPULoad, v))
}

// CPULoadHasSuffix applies the HasSuffix predicate on the "cpu_load" field.
func CPULoadHasSuffix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasSuffix(FieldCPULoad, v))
}

// CPULoadEqualFold applies the EqualFold predicate on the "cpu_load" field.
func CPULoadEqualFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEqualFold(FieldCPULoad, v))
}

// CPULoadContainsFold applies the ContainsFold predicate on the "cpu_load" field.
func CPULoadContainsFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContainsFold(FieldCPULoad, v))
}

// MemoryEQ applies the EQ predicate on the "memory" field.
func MemoryEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldMemory, v))
}

// MemoryNEQ applies the NEQ predicate on the "memory" field.
func MemoryNEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNEQ(FieldMemory, v))
}

// MemoryIn applies the In predicate on the "memory" field.
func MemoryIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIn(FieldMemory, vs...))
}

// MemoryNotIn applies the NotIn predicate on the "memory" field.
func MemoryNotIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotIn(FieldMemory, vs...))
}

// MemoryGT applies the GT predicate on the "memory" field.
func MemoryGT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGT(FieldMemory, v))
}

// MemoryGTE applies the GTE predicate on the "memory" field.
func MemoryGTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGTE(FieldMemory, v))
}

// MemoryLT applies the LT predicate on the "memory" field.
func MemoryLT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLT(FieldMemory, v))
}

// MemoryLTE applies the LTE predicate on the "memory" field.
func MemoryLTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLTE(FieldMemory, v))
}

// MemoryContains applies the Contains predicate on the "memory" field.
func MemoryContains(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContains(FieldMemory, v))
}

// MemoryHasPrefix applies the HasPrefix predicate on the "memory" field.
func MemoryHasPrefix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasPrefix(FieldMemory, v))
}

// MemoryHasSuffix applies the HasSuffix predicate on the "memory" field.
func MemoryHasSuffix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasSuffix(FieldMemory, v))
}

// MemoryEqualFold applies the EqualFold predicate on the "memory" field.
func MemoryEqualFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEqualFold(FieldMemory, v))
}

// MemoryContainsFold applies the ContainsFold predicate on the "memory" field.
func MemoryContainsFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContainsFold(FieldMemory, v))
}

// DiskEQ applies the EQ predicate on the "disk" field.
func DiskEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldDisk, v))
}

// DiskNEQ applies the NEQ predicate on the "disk" field.
func DiskNEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNEQ(FieldDisk, v))
}

// DiskIn applies the In predicate on the "disk" field.
func DiskIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIn(FieldDisk, vs...))
}

// DiskNotIn applies the NotIn predicate on the "disk" field.
func DiskNotIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotIn(FieldDisk, vs...))
}

// DiskGT applies the GT predicate on the "disk" field.
func DiskGT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGT(FieldDisk, v))
}

// DiskGTE applies the GTE predicate on the "disk" field.
func DiskGTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGTE(FieldDisk, v))
}

// DiskLT applies the LT predicate on the "disk" field.
func DiskLT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLT(FieldDisk, v))
}

// DiskLTE applies the LTE predicate on the "disk" field.
func DiskLTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLTE(FieldDisk, v))
}

// DiskContains applies the Contains predicate on the "disk" field.
func DiskContains(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContains(FieldDisk, v))
}

// DiskHasPrefix applies the HasPrefix predicate on the "disk" field.
func DiskHasPrefix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasPrefix(FieldDisk, v))
}

// DiskHasSuffix applies the HasSuffix predicate on the "disk" field.
func DiskHasSuffix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasSuffix(FieldDisk, v))
}

// DiskEqualFold applies the EqualFold predicate on the "disk" field.
func DiskEqualFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEqualFold(FieldDisk, v))
}

// DiskContainsFold applies the ContainsFold predicate on the "disk" field.
func DiskContainsFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContainsFold(FieldDisk, v))
}

// DiskIoEQ applies the EQ predicate on the "disk_io" field.
func DiskIoEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldDiskIo, v))
}

// DiskIoNEQ applies the NEQ predicate on the "disk_io" field.
func DiskIoNEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNEQ(FieldDiskIo, v))
}

// DiskIoIn applies the In predicate on the "disk_io" field.
func DiskIoIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIn(FieldDiskIo, vs...))
}

// DiskIoNotIn applies the NotIn predicate on the "disk_io" field.
func DiskIoNotIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotIn(FieldDiskIo, vs...))
}

// DiskIoGT applies the GT predicate on the "disk_io" field.
func DiskIoGT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGT(FieldDiskIo, v))
}

// DiskIoGTE applies the GTE predicate on the "disk_io" field.
func DiskIoGTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGTE(FieldDiskIo, v))
}

// DiskIoLT applies the LT predicate on the "disk_io" field.
func DiskIoLT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLT(FieldDiskIo, v))
}

// DiskIoLTE applies the LTE predicate on the "disk_io" field.
func DiskIoLTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLTE(FieldDiskIo, v))
}

// DiskIoContains applies the Contains predicate on the "disk_io" field.
func DiskIoContains(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContains(FieldDiskIo, v))
}

// DiskIoHasPrefix applies the HasPrefix predicate on the "disk_io" field.
func DiskIoHasPrefix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasPrefix(FieldDiskIo, v))
}

// DiskIoHasSuffix applies the HasSuffix predicate on the "disk_io" field.
func DiskIoHasSuffix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasSuffix(FieldDiskIo, v))
}

// DiskIoEqualFold applies the EqualFold predicate on the "disk_io" field.
func DiskIoEqualFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEqualFold(FieldDiskIo, v))
}

// DiskIoContainsFold applies the ContainsFold predicate on the "disk_io" field.
func DiskIoContainsFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContainsFold(FieldDiskIo, v))
}

// RouterEQ applies the EQ predicate on the "router" field.
func RouterEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldRouter, v))
}

// RouterNEQ applies the NEQ predicate on the "router" field.
func RouterNEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNEQ(FieldRouter, v))
}

// RouterIn applies the In predicate on the "router" field.
func RouterIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIn(FieldRouter, vs...))
}

// RouterNotIn applies the NotIn predicate on the "router" field.
func RouterNotIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotIn(FieldRouter, vs...))
}

// RouterGT applies the GT predicate on the "router" field.
func RouterGT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGT(FieldRouter, v))
}

// RouterGTE applies the GTE predicate on the "router" field.
func RouterGTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGTE(FieldRouter, v))
}

// RouterLT applies the LT predicate on the "router" field.
func RouterLT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLT(FieldRouter, v))
}

// RouterLTE applies the LTE predicate on the "router" field.
func RouterLTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLTE(FieldRouter, v))
}

// RouterContains applies the Contains predicate on the "router" field.
func RouterContains(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContains(FieldRouter, v))
}

// RouterHasPrefix applies the HasPrefix predicate on the "router" field.
func RouterHasPrefix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasPrefix(FieldRouter, v))
}

// RouterHasSuffix applies the HasSuffix predicate on the "router" field.
func RouterHasSuffix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasSuffix(FieldRouter, v))
}

// RouterEqualFold applies the EqualFold predicate on the "router" field.
func RouterEqualFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEqualFold(FieldRouter, v))
}

// RouterContainsFold applies the ContainsFold predicate on the "router" field.
func RouterContainsFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContainsFold(FieldRouter, v))
}

// NetStatsEQ applies the EQ predicate on the "net_stats" field.
func NetStatsEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldNetStats, v))
}

// NetStatsNEQ applies the NEQ predicate on the "net_stats" field.
func NetStatsNEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNEQ(FieldNetStats, v))
}

// NetStatsIn applies the In predicate on the "net_stats" field.
func NetStatsIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIn(FieldNetStats, vs...))
}

// NetStatsNotIn applies the NotIn predicate on the "net_stats" field.
func NetStatsNotIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotIn(FieldNetStats, vs...))
}

// NetStatsGT applies the GT predicate on the "net_stats" field.
func NetStatsGT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGT(FieldNetStats, v))
}

// NetStatsGTE applies the GTE predicate on the "net_stats" field.
func NetStatsGTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGTE(FieldNetStats, v))
}

// NetStatsLT applies the LT predicate on the "net_stats" field.
func NetStatsLT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLT(FieldNetStats, v))
}

// NetStatsLTE applies the LTE predicate on the "net_stats" field.
func NetStatsLTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLTE(FieldNetStats, v))
}

// NetStatsContains applies the Contains predicate on the "net_stats" field.
func NetStatsContains(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContains(FieldNetStats, v))
}

// NetStatsHasPrefix applies the HasPrefix predicate on the "net_stats" field.
func NetStatsHasPrefix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasPrefix(FieldNetStats, v))
}

// NetStatsHasSuffix applies the HasSuffix predicate on the "net_stats" field.
func NetStatsHasSuffix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasSuffix(FieldNetStats, v))
}

// NetStatsEqualFold applies the EqualFold predicate on the "net_stats" field.
func NetStatsEqualFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEqualFold(FieldNetStats, v))
}

// NetStatsContainsFold applies the ContainsFold predicate on the "net_stats" field.
func NetStatsContainsFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContainsFold(FieldNetStats, v))
}

// ProcessesEQ applies the EQ predicate on the "processes" field.
func ProcessesEQ(v int32) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldProcesses, v))
}

// ProcessesNEQ applies the NEQ predicate on the "processes" field.
func ProcessesNEQ(v int32) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNEQ(FieldProcesses, v))
}

// ProcessesIn applies the In predicate on the "processes" field.
func ProcessesIn(vs ...int32) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIn(FieldProcesses, vs...))
}

// ProcessesNotIn applies the NotIn predicate on the "processes" field.
func ProcessesNotIn(vs ...int32) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotIn(FieldProcesses, vs...))
}

// ProcessesGT applies the GT predicate on the "processes" field.
func ProcessesGT(v int32) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGT(FieldProcesses, v))
}

// ProcessesGTE applies the GTE predicate on the "processes" field.
func ProcessesGTE(v int32) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGTE(FieldProcesses, v))
}

// ProcessesLT applies the LT predicate on the "processes" field.
func ProcessesLT(v int32) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLT(FieldProcesses, v))
}

// ProcessesLTE applies the LTE predicate on the "processes" field.
func ProcessesLTE(v int32) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLTE(FieldProcesses, v))
}

// ZombieProcsEQ applies the EQ predicate on the "zombie_procs" field.
func ZombieProcsEQ(v int32) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldZombieProcs, v))
}

// ZombieProcsNEQ applies the NEQ predicate on the "zombie_procs" field.
func ZombieProcsNEQ(v int32) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNEQ(FieldZombieProcs, v))
}

// ZombieProcsIn applies the In predicate on the "zombie_procs" field.
func ZombieProcsIn(vs ...int32) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIn(FieldZombieProcs, vs...))
}

// ZombieProcsNotIn applies the NotIn predicate on the "zombie_procs" field.
func ZombieProcsNotIn(vs ...int32) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotIn(FieldZombieProcs, vs...))
}

// ZombieProcsGT applies the GT predicate on the "zombie_procs" field.
func ZombieProcsGT(v int32) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGT(FieldZombieProcs, v))
}

// ZombieProcsGTE applies the GTE predicate on the "zombie_procs" field.
func ZombieProcsGTE(v int32) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGTE(FieldZombieProcs, v))
}

// ZombieProcsLT applies the LT predicate on the "zombie_procs" field.
func ZombieProcsLT(v int32) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLT(FieldZombieProcs, v))
}

// ZombieProcsLTE applies the LTE predicate on the "zombie_procs" field.
func ZombieProcsLTE(v int32) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLTE(FieldZombieProcs, v))
}

// TopProcessesEQ applies the EQ predicate on the "top_processes" field.
func TopProcessesEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldTopProcesses, v))
}

// TopProcessesNEQ applies the NEQ predicate on the "top_processes" field.
func TopProcessesNEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNEQ(FieldTopProcesses, v))
}

// TopProcessesIn applies the In predicate on the "top_processes" field.
func TopProcessesIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIn(FieldTopProcesses, vs...))
}

// TopProcessesNotIn applies the NotIn predicate on the "top_processes" field.
func TopProcessesNotIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotIn(FieldTopProcesses, vs...))
}

// TopProcessesGT applies the GT predicate on the "top_processes" field.
func TopProcessesGT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGT(FieldTopProcesses, v))
}

// TopProcessesGTE applies the GTE predicate on the "top_processes" field.
func TopProcessesGTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGTE(FieldTopProcesses, v))
}

// TopProcessesLT applies the LT predicate on the "top_processes" field.
func TopProcessesLT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLT(FieldTopProcesses, v))
}

// TopProcessesLTE applies the LTE predicate on the "top_processes" field.
func TopProcessesLTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLTE(FieldTopProcesses, v))
}

// TopProcessesContains applies the Contains predicate on the "top_processes" field.
func TopProcessesContains(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContains(FieldTopProcesses, v))
}

// TopProcessesHasPrefix applies the HasPrefix predicate on the "top_processes" field.
func TopProcessesHasPrefix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasPrefix(FieldTopProcesses, v))
}

// TopProcessesHasSuffix applies the HasSuffix predicate on the "top_processes" field.
func TopProcessesHasSuffix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasSuffix(FieldTopProcesses, v))
}

// TopProcessesEqualFold applies the EqualFold predicate on the "top_processes" field.
func TopProcessesEqualFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEqualFold(FieldTopProcesses, v))
}

// TopProcessesContainsFold applies the ContainsFold predicate on the "top_processes" field.
func TopProcessesContainsFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContainsFold(FieldTopProcesses, v))
}

// EnvEQ applies the EQ predicate on the "env" field.
func EnvEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldEnv, v))
}

// EnvNEQ applies the NEQ predicate on the "env" field.
func EnvNEQ(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNEQ(FieldEnv, v))
}

// EnvIn applies the In predicate on the "env" field.
func EnvIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIn(FieldEnv, vs...))
}

// EnvNotIn applies the NotIn predicate on the "env" field.
func EnvNotIn(vs ...string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotIn(FieldEnv, vs...))
}

// EnvGT applies the GT predicate on the "env" field.
func EnvGT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGT(FieldEnv, v))
}

// EnvGTE applies the GTE predicate on the "env" field.
func EnvGTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGTE(FieldEnv, v))
}

// EnvLT applies the LT predicate on the "env" field.
func EnvLT(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLT(FieldEnv, v))
}

// EnvLTE applies the LTE predicate on the "env" field.
func EnvLTE(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLTE(FieldEnv, v))
}

// EnvContains applies the Contains predicate on the "env" field.
func EnvContains(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContains(FieldEnv, v))
}

// EnvHasPrefix applies the HasPrefix predicate on the "env" field.
func EnvHasPrefix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasPrefix(FieldEnv, v))
}

// EnvHasSuffix applies the HasSuffix predicate on the "env" field.
func EnvHasSuffix(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldHasSuffix(FieldEnv, v))
}

// EnvIsNil applies the IsNil predicate on the "env" field.
func EnvIsNil() predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIsNull(FieldEnv))
}

// EnvNotNil applies the NotNil predicate on the "env" field.
func EnvNotNil() predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotNull(FieldEnv))
}

// EnvEqualFold applies the EqualFold predicate on the "env" field.
func EnvEqualFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEqualFold(FieldEnv, v))
}

// EnvContainsFold applies the ContainsFold predicate on the "env" field.
func EnvContainsFold(v string) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldContainsFold(FieldEnv, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CaseyInspections) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CaseyInspections) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CaseyInspections) predicate.CaseyInspections {
	return predicate.CaseyInspections(sql.NotPredicates(p))
}
